# active [0,1]: 0 disables the rule; 1 enables the rule. By default it is enabled.
# type [0,1]: 0 reports an warning; 1 reports an error.
# value: value to use for the rule.
header_max_length:
  active: true
  type: 0 
  value: 50
header_is_not_empty:
  active: true
  type: 1
  value: 0
header_starts_with_tag:
  active: true
  type: 1
  value: 'vuln-detect'
header_has_weakness:
  active: true
  type: 1
header_has_severity:
  active: true
  type: 0 
summary_has_what:
  active: true
  type: 1 
summary_what_identifies_weakness:
  active: true
  type: 0
summary_has_why:
  active: true
  type: 1 
  value: 'why'
summary_has_how:
  active: true
  type: 1 
  value: 'how'
summary_has_when: 
  active: true
  type: 0 
  value: 'when'
summary_max_length:
  active: true
  type: 0
  value: 150
explanation_is_not_empty:
  active: true
  type: 1
  value: 0
explanation_has_weakness:
  active: true
  type: 1
explanation_has_severity:
  active: true
  type: 1
explanation_has_location_file:
  active: true
  type: 1
explanation_has_location_method:
  active: true
  type: 1
explanation_has_location_line:
  active: true
  type: 1
explanation_has_unchecked_vars:
  active: true
  type: 0
explanation_has_checked_vars:
  active: true
  type: 0
explanation_has_sources:
  active: true
  type: 0
explanation_has_sinks:
  active: true
  type: 0
reporter_has_reported_by:
  active: true
  type: 0
  value: 'reported-by'
reporter_has_co_authored_by:
  active: true
  type: 0
  value: 'co-authored-by'
reporter_identifies_detection_strategy:
  active: true
  type: 1